name: poolmate
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.1.0
  flutter_neumorphic_plus: ^3.4.0
  syncfusion_flutter_gauges: ^20.3.47
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  page_transition: ^2.0.9
  clay_containers: ^0.3.4
  flutter_svg_provider: ^1.0.7
  http: ^1.2.2
  email_auth: ^2.0.0
  flutter_neumorphic: ^3.2.0 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
